<?php

function acf_featured_content()
{

    return array(
  		array(
  			'key' => 'field_6182f613311cf',
  			'label' => 'Featured Content',
  			'name' => '',
  			'type' => 'tab',
  			'instructions' => '',
  			'required' => 0,
  			'conditional_logic' => 0,
  			'wrapper' => array(
  				'width' => '',
  				'class' => '',
  				'id' => '',
  			),
  			'placement' => 'top',
  			'endpoint' => 0,
  		),
  		array(
  			'key' => 'field_6182f61f311d0',
  			'label' => 'Featured Content Items',
  			'name' => 'featured_content_items',
  			'type' => 'repeater',
  			'instructions' => '',
  			'required' => 0,
  			'conditional_logic' => 0,
  			'wrapper' => array(
  				'width' => '',
  				'class' => '',
  				'id' => '',
  			),
  			'collapsed' => 'field_6182f642311d1',
  			'min' => 0,
  			'max' => 6,
  			'layout' => 'block',
  			'button_label' => 'Add Row',
  			'sub_fields' => array(
  				array(
  					'key' => 'field_6182f642311d1',
  					'label' => 'Heading',
  					'name' => 'item_name',
  					'type' => 'text',
  					'instructions' => '*Max 50 characters',
  					'required' => 0,
  					'conditional_logic' => 0,
  					'wrapper' => array(
  						'width' => '25',
  						'class' => '',
  						'id' => '',
  					),
  					'default_value' => '',
  					'placeholder' => '',
  					'prepend' => '',
  					'append' => '',
  					'maxlength' => 50,
  					'parent_repeater' => 'field_6182f61f311d0',
  				),
  				// array(
  				// 	'key' => 'field_623a23d6a6a26',
  				// 	'label' => 'Subheading',
  				// 	'name' => 'item_subheading',
  				// 	'type' => 'text',
  				// 	'instructions' => '*Max 50 characters',
  				// 	'required' => 0,
  				// 	'conditional_logic' => 0,
  				// 	'wrapper' => array(
  				// 		'width' => '25',
  				// 		'class' => '',
  				// 		'id' => '',
  				// 	),
  				// 	'default_value' => '',
  				// 	'placeholder' => '',
  				// 	'prepend' => '',
  				// 	'append' => '',
  				// 	'maxlength' => 50,
  				// 	'parent_repeater' => 'field_6182f61f311d0',
  				// ),
  				// array(
  				// 	'key' => 'field_626818f2de636',
  				// 	'label' => 'Content',
  				// 	'name' => 'content',
  				// 	'type' => 'textarea',
  				// 	'instructions' => '*text that appears on hover, Max 200 characters',
  				// 	'required' => 0,
  				// 	'conditional_logic' => 0,
  				// 	'wrapper' => array(
  				// 		'width' => '100',
  				// 		'class' => '',
  				// 		'id' => '',
  				// 	),
  				// 	'default_value' => '',
  				// 	'placeholder' => '',
  				// 	'maxlength' => '',
  				// 	'rows' => 4,
  				// 	'new_lines' => '',
  				// 	'parent_repeater' => 'field_6182f61f311d0',
  				// ),
  				array(
  					'key' => 'field_6182f6b9311d3',
  					'label' => 'Image',
  					'name' => 'image',
  					'type' => 'image',
  					'instructions' => '',
  					'required' => 0,
  					'conditional_logic' => 0,
  					'wrapper' => array(
  						'width' => '25',
  						'class' => '',
  						'id' => '',
  					),
  					'return_format' => 'array',
  					'preview_size' => 'medium',
  					'library' => 'all',
  					'min_width' => '',
  					'min_height' => '',
  					'min_size' => '',
  					'max_width' => '',
  					'max_height' => '',
  					'max_size' => '',
  					'mime_types' => '',
  					'parent_repeater' => 'field_6182f61f311d0',
  				),
  				array(
  					'key' => 'field_6196abe21f65f',
  					'label' => 'Link',
  					'name' => 'link',
  					'type' => 'link',
  					'instructions' => '',
  					'required' => 0,
  					'conditional_logic' => 0,
  					'wrapper' => array(
  						'width' => '25',
  						'class' => '',
  						'id' => '',
  					),
  					'return_format' => 'array',
  					'parent_repeater' => 'field_6182f61f311d0',
  				),
  			),
  			'rows_per_page' => 20,
  		),
    );
}
